'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Enfermedade
    Public Property idEnfermedades As Integer
    Public Property nombre As String
    Public Property descripcion As String

    Public Overridable Property EnfermedadesXPacientes As ICollection(Of EnfermedadesXPaciente) = New HashSet(Of EnfermedadesXPaciente)

End Class
