'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EnfermedadesXPaciente
    Public Property dniPaciente As Integer
    Public Property idEnfermedad As Integer
    Public Property descripcion As String

    Public Overridable Property Enfermedade As Enfermedade
    Public Overridable Property Paciente As Paciente

End Class
