'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Especialidad
    Public Property idEspecialidad As Integer
    Public Property nombre As String
    Public Property descripcion As String

    Public Overridable Property MedicosXEspecialidads As ICollection(Of MedicosXEspecialidad) = New HashSet(Of MedicosXEspecialidad)

End Class
