'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Factura
    Public Property nroFactura As Integer
    Public Property fecha As Nullable(Of Date)
    Public Property dniPaciente As Nullable(Of Integer)
    Public Property legajoOdontologo As Nullable(Of Integer)
    Public Property idObraSocial As Nullable(Of Integer)
    Public Property idPlan As Nullable(Of Integer)

    Public Overridable Property DetalleFacturas As ICollection(Of DetalleFactura) = New HashSet(Of DetalleFactura)
    Public Overridable Property Odontologo As Odontologo
    Public Overridable Property Paciente As Paciente
    Public Overridable Property Plane As Plane

End Class
