'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HistoriaClinica
    Public Property dniPaciente As Integer
    Public Property idPrestacion As Integer
    Public Property fecha As Date
    Public Property idUbicacion As Nullable(Of Integer)
    Public Property idTipo As Nullable(Of Integer)
    Public Property observaciones As String

    Public Overridable Property Paciente As Paciente
    Public Overridable Property Prestacione As Prestacione
    Public Overridable Property TipoDiente As TipoDiente
    Public Overridable Property Ubicacion As Ubicacion

End Class
