'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ObraSocial
    Public Property idOS As Integer
    Public Property nombre As String

    Public Overridable Property Planes As ICollection(Of Plane) = New HashSet(Of Plane)

End Class
