'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ObraSocialXPaciente
    Public Property idNroAfiliado As Integer
    Public Property idPlan As Integer
    Public Property idObraSocial As Integer
    Public Property dniPaciente As Integer

    Public Overridable Property Paciente As Paciente
    Public Overridable Property Plane As Plane

End Class
