'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Odontologo
    Public Property legajo As Integer
    Public Property dniOdontologo As Nullable(Of Integer)
    Public Property apellido As String
    Public Property nombre As String
    Public Property sexo As String
    Public Property fechaNacimiento As Nullable(Of Date)
    Public Property eMail As String
    Public Property domicilio As String
    Public Property nroMatricula As Nullable(Of Integer)
    Public Property fechaIngreso As Nullable(Of Date)
    Public Property activo As String
    Public Property telContacto As String

    Public Overridable Property Facturas As ICollection(Of Factura) = New HashSet(Of Factura)
    Public Overridable Property Recetas As ICollection(Of Receta) = New HashSet(Of Receta)

End Class
