'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Paciente
    Public Property dniPaciente As Integer
    Public Property nombre As String
    Public Property apellido As String
    Public Property sexo As String
    Public Property fechaNacimiento As Nullable(Of Date)
    Public Property telContacto As String
    Public Property activo As String

    Public Overridable Property EnfermedadesXPacientes As ICollection(Of EnfermedadesXPaciente) = New HashSet(Of EnfermedadesXPaciente)
    Public Overridable Property Facturas As ICollection(Of Factura) = New HashSet(Of Factura)
    Public Overridable Property HistoriaClinicas As ICollection(Of HistoriaClinica) = New HashSet(Of HistoriaClinica)
    Public Overridable Property ObraSocialXPacientes As ICollection(Of ObraSocialXPaciente) = New HashSet(Of ObraSocialXPaciente)
    Public Overridable Property Recetas As ICollection(Of Receta) = New HashSet(Of Receta)

End Class
