'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Plane
    Public Property idPlan As Integer
    Public Property idObraSocial As Integer
    Public Property nombre As String

    Public Overridable Property Facturas As ICollection(Of Factura) = New HashSet(Of Factura)
    Public Overridable Property ObraSocial As ObraSocial
    Public Overridable Property ObraSocialXPacientes As ICollection(Of ObraSocialXPaciente) = New HashSet(Of ObraSocialXPaciente)
    Public Overridable Property PrestacionesPorPlans As ICollection(Of PrestacionesPorPlan) = New HashSet(Of PrestacionesPorPlan)

End Class
