'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PrestacionesPorPlan
    Public Property idPlan As Integer
    Public Property idObraSocial As Integer
    Public Property idPrestacion As Integer
    Public Property montoCubierto As Nullable(Of Double)

    Public Overridable Property Plane As Plane

End Class
