'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Prestacione
    Public Property idPrestacion As Integer
    Public Property nombre As String
    Public Property descripcion As String
    Public Property precio As Nullable(Of Double)
    Public Property duracion As Nullable(Of Integer)

    Public Overridable Property DetalleFacturas As ICollection(Of DetalleFactura) = New HashSet(Of DetalleFactura)
    Public Overridable Property HistoriaClinicas As ICollection(Of HistoriaClinica) = New HashSet(Of HistoriaClinica)

End Class
