'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TipoDiente
    Public Property idTipo As Integer
    Public Property nombre As String

    Public Overridable Property HistoriaClinicas As ICollection(Of HistoriaClinica) = New HashSet(Of HistoriaClinica)

End Class
