'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Turno
    Public Property legajoOdontologo As Integer
    Public Property idPaciente As Integer
    Public Property fecha As Date
    Public Property hora As String
    Public Property idPrestacion As Integer
    Public Property idEstado As Integer
    Public Property descripcion As String

End Class
